# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - run:
       echo $PATH
       node -v
       npm -v 
       python --version
       java --version
       go -v
       git -v
